# Generated by Django 5.2.3 on 2025-06-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email', 'username']},
        ),
    ]
